language: node_js
node_js:
  - "12.2.0"
dist: trusty
sudo: required
branches:
  only:
  - master
addons:
  chrome: stable

cache:
  directories:
     - ./node_modules

install:
  - travis_wait npm install
  - travis_wait npm install -g @angular/cli@10.0.0

script:
- npm run test:headless
- npm run build
# npm run e2e